
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 151
#define YY_END_OF_BUFFER 152
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[506] =
    {   0,
        0,    0,    6,    6,  152,  150,    2,    1,   43,  150,
      150,   34,   37,  150,   21,   22,   32,   30,   74,   31,
       28,   33,  143,  143,   24,   23,   46,   45,   47,   26,
      140,  140,   17,   19,   35,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,   13,   39,   15,   41,  151,
        6,  151,  151,    2,   64,    0,  148,    0,    0,   52,
       16,   68,   55,    0,  146,    0,   50,   72,   48,   73,
       49,   76,   29,    0,  144,    3,    4,   51,  144,  142,
      143,    0,  143,  143,    0,   27,   20,   14,   18,   59,

       66,   63,   67,   60,  140,    0,    0,   53,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,   90,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  103,
      140,  140,  140,  140,  140,  140,  140,   71,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,   57,   70,    6,    0,
        0,    0,    0,    0,    0,  148,    0,    0,    0,  146,
        0,   75,   25,    0,  144,  142,  142,    0,  145,  143,
      143,  141,   61,   62,    0,  149,    0,    0,  147,    0,
       69,   77,  140,  140,  140,  140,  140,  140,  140,  140,

      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  100,  140,  140,  140,  105,  140,  140,  140,
      109,   44,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      128,  140,  140,  140,  140,  140,  140,  140,  140,  140,
       36,   12,    0,    0,    0,    0,    0,    0,    0,  144,
      142,  142,  145,  141,  141,    0,  149,    0,    0,  147,
        0,  140,   78,  140,  140,   79,  140,   81,  140,   83,
      140,  140,  140,  140,  140,  140,  140,  140,   93,   94,
      140,  140,  140,  140,  140,  140,  102,  140,  106,  140,

      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  125,  140,  127,
      140,  140,  140,  140,  140,  136,  140,  140,  140,  140,
        0,    0,    0,    0,    0,    0,  141,  141,  140,  140,
       40,   80,   82,   84,   42,   85,  140,  140,  140,  140,
      140,  140,  140,  140,   98,   99,  140,  140,  140,  140,
      140,  140,   58,  140,  140,  140,  140,  140,  140,  117,
      140,  140,  140,  140,  140,  140,  126,  140,  140,  140,
      132,  140,  134,  140,  140,  140,  139,  140,    0,    0,
        0,    0,    0,    0,   56,   38,  140,  140,  140,   89,

       91,  140,  140,   96,   97,  101,  104,  140,  140,   65,
      140,  140,  140,  113,  140,  140,  116,  118,  119,  120,
      122,  123,  140,  140,  130,  140,  140,  140,  140,  140,
       54,    0,    0,    0,    0,    0,    0,  140,  140,   88,
      140,  140,  107,  140,  140,  111,  140,  140,  140,  140,
      140,  129,  140,  140,  135,  140,  138,    0,    9,    0,
        0,    0,    5,  140,   87,  140,   95,  140,  110,  140,
      114,  140,  140,  124,  131,  133,  137,    0,    0,    0,
       10,  140,  140,  108,  112,  140,  140,    8,   11,    0,
       86,  140,  140,  140,    7,  140,  140,  121,   92,  140,

      140,  140,  140,  115,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   29,   29,   29,   30,   31,
       32,   32,   32,   32,   32,   33,   32,   32,   32,   32,
       32,   32,   32,   32,   34,   32,   32,   35,   32,   32,
       36,   37,   38,   39,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   32,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[70] =
    {   0,
        1,    2,    2,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    4,    4,    4,    4,    1,    1,    1,    1,    4,
        3,    3,    3,    3,    3,    3,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[518] =
    {   0,
        0,    0,   65,   66,  687,  688,   72,  688,  660,   68,
      636,   52,   70,   70,  688,  688,  658,   67,  688,   71,
       81,   90,  108,  101,   60,  688,   85,  657,   86,  688,
        0,  107,  688,  688,  656,   79,   91,  103,  102,   64,
      119,  627,  109,  626,  619,  124,  117,   29,  633,  131,
      137,  105,  132,  140,  623,  688,   66,  688,  688,  688,
      145,    0,  149,  195,  688,   99,  688,  184,  623,  688,
      688,  688,  688,  138,  688,  199,  688,  688,  688,  688,
      688,  661,  688,  656,  192,  688,  688,  688,  196,  228,
      233,  213,  143,  173,    0,  688,  688,  688,  688,  647,

      688,  688,  688,  646,    0,  182,  194,  688,  627,  618,
      610,  609,  613,  621,  150,  624,  623,  187,  169,  603,
      609,  603,  600,  197,  608,  604,  600,  607,  596,    0,
      206,  601,  594,  600,  589,  591,  604,  608,  210,  605,
      221,  592,  222,  203,  596,  592,  225,  211,  588,  223,
      593,  584,  234,  592,  590,  581,  688,  688,  271,  630,
      233,  578,  581,  575,  270,  279,  291,  590,  278,  284,
      294,  688,  688,  289,  688,  262,  266,  280,  292,  688,
      688,  285,  688,  688,  296,  688,  317,  297,  688,  324,
      592,    0,  577,  191,  579,  588,  583,  584,  569,  567,

      569,  281,  582,  577,  579,  579,  574,  566,  275,  572,
      558,  574,    0,  569,  559,  563,    0,  564,  569,  564,
        0,  568,  550,  561,  544,  545,  552,  553,  548,  540,
      542,  545,  552,  537,  535,  535,  538,  534,  537,  545,
        0,  544,  534,  538,  533,  526,  540,  542,  541,  530,
      540,  572,  519,  528,  517,  517,  517,  522,  326,  329,
      688,  688,  688,  298,  304,  334,  335,  349,  333,  342,
      354,  527,    0,  518,  513,    0,  519,    0,  520,    0,
      509,  515,  506,  515,  503,  503,  510,  508,    0,    0,
      510,  501,  500,  511,  496,  501,    0,  500,    0,  510,

      493,  505,  508,  492,  506,  501,  496,  486,  484,  485,
      482,  495,  485,  489,  494,  493,  484,    0,  472,    0,
      315,  480,  485,  484,  470,    0,  470,  471,  482,  481,
      481,  472,  466,  463,  472,  460,  688,  688,  463,  474,
        0,    0,    0,    0,    0,  477,  463,  464,  469,  468,
      463,  468,  451,  456,    0,    0,  464,  462,  455,  450,
      448,  444,    0,  443,  458,  457,  440,  453,  444,    0,
      452,  449,  451,  434,  444,  450,    0,  445,  445,  447,
        0,  434,    0,  445,  436,  444,    0,  427,  431,  436,
      435,  422,  425,  433,    0,    0,  433,  415,  415,    0,

        0,  430,  423,    0,    0,    0,    0,  426,  429,    0,
      415,  423,  408,    0,  421,  408,    0,    0,    0,  424,
        0,    0,  404,  416,    0,  409,  415,  408,  407,  398,
        0,  407,  428,  413,  408,  405,  406,  409,  404,    0,
      408,  388,    0,  403,  388,    0,  399,  386,  387,  398,
      395,    0,  394,  394,    0,  392,    0,  394,  688,  383,
      393,  380,  688,  332,    0,  346,    0,  343,    0,  343,
        0,  328,  343,    0,    0,    0,    0,  356,  355,  329,
      688,  319,  336,    0,    0,  331,  316,  688,  688,  346,
        0,  311,  308,  307,  688,  304,  171,    0,    0,  153,

      143,  109,   61,    0,  688,  391,  395,  399,  401,  405,
      409,  413,   97,  417,  421,  425,  429
    } ;

static yyconst flex_int16_t yy_def[518] =
    {   0,
      505,    1,  506,  506,  505,  505,  505,  505,  505,  507,
      505,  505,  505,  508,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      509,  509,  505,  505,  505,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  505,  505,  505,  505,  505,
      505,  510,  505,  505,  505,  507,  505,  511,  505,  505,
      505,  505,  505,  508,  505,  512,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  513,  505,  505,  505,  505,  505,

      505,  505,  505,  505,  509,  514,  515,  505,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  505,  505,  505,  510,
      505,  505,  505,  505,  507,  507,  511,  505,  508,  508,
      512,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  513,  505,  505,  514,  505,  516,  515,  505,  517,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,

      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  510,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  514,  514,  516,  515,  515,
      517,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,

      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      505,  505,  505,  505,  505,  505,  505,  505,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  505,  505,
      505,  505,  505,  505,  509,  509,  509,  509,  509,  509,

      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  505,  505,  505,  505,  505,  505,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  505,  505,  505,
      505,  505,  505,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  505,  505,  505,
      505,  509,  509,  509,  509,  509,  509,  505,  505,  505,
      509,  509,  509,  509,  505,  509,  509,  509,  509,  509,

      509,  509,  509,  509,    0,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505
    } ;

static yyconst flex_int16_t yy_nxt[758] =
    {   0,
        6,    7,    8,    7,    7,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   24,   25,   26,   27,   28,   29,   30,   31,   31,
       31,   31,   32,   31,   31,   33,    6,   34,   35,   31,
       36,   37,   38,   39,   40,   41,   42,   31,   43,   31,
       44,   45,   46,   47,   48,   31,   49,   50,   51,   52,
       53,   54,   55,   31,   31,   56,   57,   58,   59,   61,
       61,   62,   62,   64,   67,   64,   64,   70,   71,   72,
       75,   78,   96,   61,   61,  139,   97,   80,  140,   63,
       63,  157,   79,   98,   83,   73,   81,   82,   84,  182,

       85,   85,   85,   86,   68,   67,   76,   99,   87,  100,
      101,  103,  104,  106,  122,   88,  123,  107,   89,  504,
       91,   91,   91,   61,   61,   89,  124,   90,   90,   91,
       92,  109,  158,   93,   94,   68,  110,   92,  111,  112,
       93,   94,   95,  115,  113,   92,  119,  114,   75,  159,
      116,   93,   92,  117,  130,  120,  118,  150,   93,  125,
       94,  131,  151,  159,  134,  121,  503,   94,  135,  126,
       95,  137,  127,  138,   76,  128,  180,  136,  142,  143,
      152,  146,  154,  502,  147,  153,   66,  155,  186,  144,
      166,  161,  145,  148,  162,  501,   64,  163,   64,   64,

      149,   74,  180,  159,  189,  181,  164,  197,  198,  170,
      500,   85,   85,   85,  203,   85,   85,   85,  187,  204,
      167,  174,  175,  181,  175,  174,  175,  178,  175,  178,
      190,  274,  179,  179,  179,  171,  174,  175,  201,  202,
      174,  175,  175,  234,  275,   89,  175,   90,   90,   91,
       89,  209,   91,   91,   91,  210,  216,   92,  225,  235,
      176,  177,   92,  226,  217,   93,   94,  228,  232,  229,
      240,  243,   92,  238,  241,  159,   67,   92,  176,  230,
      244,  239,  247,   93,  248,   67,  233,  177,   75,  159,
      253,  254,   94,   66,   75,  261,   74,  166,  262,  179,

      179,  179,  186,  259,  170,  259,   68,  189,  260,  260,
      260,  179,  179,  179,   76,   68,  262,  264,  265,  185,
       76,  261,  263,  267,  263,  291,  188,  167,  292,  159,
      171,  337,  187,  190,  270,  264,  338,  263,  283,  284,
      186,  186,  263,  189,  265,  260,  260,  260,  260,  260,
      260,  185,  189,  268,  338,  267,  188,  337,  378,  175,
      271,  175,  499,  379,  270,  498,  497,  380,  496,  190,
      187,  187,  495,  494,  175,  493,  492,  491,  190,  175,
      490,  489,  488,  487,  486,  268,  485,  484,  483,  482,
      271,   60,   60,   60,   60,   66,   66,   66,   66,   74,

       74,   74,   74,  105,  105,  160,  481,  160,  160,  165,
      165,  165,  165,  169,  169,  169,  169,  185,  185,  185,
      185,  188,  188,  188,  188,  266,  266,  266,  266,  269,
      269,  269,  269,  480,  479,  478,  477,  476,  475,  474,
      473,  472,  471,  470,  469,  468,  467,  466,  465,  464,
      463,  462,  461,  460,  459,  458,  457,  456,  455,  454,
      453,  452,  451,  450,  449,  448,  447,  446,  445,  444,
      443,  442,  441,  440,  439,  438,  437,  436,  435,  434,
      433,  432,  431,  430,  429,  428,  427,  426,  425,  424,
      423,  422,  421,  420,  419,  418,  417,  416,  415,  414,

      413,  412,  411,  410,  409,  408,  407,  406,  405,  404,
      403,  402,  401,  400,  399,  398,  397,  396,  395,  394,
      393,  392,  391,  390,  389,  388,  387,  386,  385,  384,
      383,  382,  381,  377,  376,  375,  374,  373,  372,  371,
      370,  369,  368,  367,  366,  365,  364,  363,  362,  361,
      360,  359,  358,  357,  356,  355,  354,  353,  352,  351,
      350,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      340,  339,  336,  335,  334,  333,  332,  331,  252,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  310,

      309,  308,  307,  306,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  296,  295,  294,  293,  290,  289,  288,
      287,  286,  285,  282,  281,  280,  279,  278,  277,  276,
      273,  272,  258,  257,  256,  255,  252,  251,  250,  249,
      246,  245,  242,  237,  236,  231,  227,  224,  223,  222,
      221,  220,  219,  218,  215,  214,  213,  212,  211,  208,
      207,  206,  205,  200,  199,  196,  195,  194,  193,  192,
      191,  184,  183,  173,  172,  168,  156,  141,  133,  132,
      129,  108,  102,   77,   69,   65,  505,    5,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,

      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505
    } ;

static yyconst flex_int16_t yy_chk[758] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    3,    4,    7,   10,    7,    7,   12,   12,   13,
       14,   18,   25,    3,    4,   48,   25,   20,   48,    3,
        4,   57,   18,   27,   21,   13,   20,   20,   21,  513,

       21,   21,   21,   22,   10,   66,   14,   27,   22,   27,
       27,   29,   29,   32,   40,   22,   40,   32,   24,  503,
       24,   24,   24,    3,    4,   23,   40,   23,   23,   23,
       24,   36,   57,   24,   24,   66,   36,   23,   36,   37,
       23,   23,   23,   38,   37,   24,   39,   37,   74,   61,
       38,   24,   23,   38,   43,   39,   38,   52,   23,   41,
       24,   43,   52,   61,   46,   39,  502,   23,   46,   41,
       23,   47,   41,   47,   74,   41,   93,   46,   50,   50,
       53,   51,   54,  501,   51,   53,   68,   54,  106,   50,
       68,   63,   50,   51,   63,  500,   64,   63,   64,   64,

       51,   76,   93,   61,  107,   94,   63,  115,  115,   76,
      497,   85,   85,   85,  119,   89,   89,   89,  106,  119,
       68,   85,   85,   94,   85,   89,   89,   92,   89,   92,
      107,  194,   92,   92,   92,   76,   85,   85,  118,  118,
       89,   89,   85,  144,  194,   90,   89,   90,   90,   90,
       91,  124,   91,   91,   91,  124,  131,   90,  139,  144,
       90,   90,   91,  139,  131,   91,   91,  141,  143,  141,
      148,  150,   90,  147,  148,  159,  165,   91,   90,  141,
      150,  147,  153,   91,  153,  166,  143,   90,  169,  159,
      161,  161,   91,  167,  170,  176,  171,  167,  177,  178,

      178,  178,  185,  174,  171,  174,  165,  188,  174,  174,
      174,  179,  179,  179,  169,  166,  177,  182,  182,  187,
      170,  176,  179,  187,  179,  209,  190,  167,  209,  159,
      171,  264,  185,  188,  190,  182,  265,  179,  202,  202,
      266,  267,  179,  269,  182,  259,  259,  259,  260,  260,
      260,  268,  270,  187,  265,  268,  271,  264,  321,  260,
      190,  260,  496,  321,  271,  494,  493,  321,  492,  269,
      266,  267,  490,  487,  260,  486,  483,  482,  270,  260,
      480,  479,  478,  473,  472,  268,  470,  468,  466,  464,
      271,  506,  506,  506,  506,  507,  507,  507,  507,  508,

      508,  508,  508,  509,  509,  510,  462,  510,  510,  511,
      511,  511,  511,  512,  512,  512,  512,  514,  514,  514,
      514,  515,  515,  515,  515,  516,  516,  516,  516,  517,
      517,  517,  517,  461,  460,  458,  456,  454,  453,  451,
      450,  449,  448,  447,  445,  444,  442,  441,  439,  438,
      437,  436,  435,  434,  433,  432,  430,  429,  428,  427,
      426,  424,  423,  420,  416,  415,  413,  412,  411,  409,
      408,  403,  402,  399,  398,  397,  394,  393,  392,  391,
      390,  389,  388,  386,  385,  384,  382,  380,  379,  378,
      376,  375,  374,  373,  372,  371,  369,  368,  367,  366,

      365,  364,  362,  361,  360,  359,  358,  357,  354,  353,
      352,  351,  350,  349,  348,  347,  346,  340,  339,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  325,
      324,  323,  322,  319,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  300,  298,  296,  295,  294,  293,  292,  291,  288,
      287,  286,  285,  284,  283,  282,  281,  279,  277,  275,
      274,  272,  258,  257,  256,  255,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  245,  244,  243,  242,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,

      229,  228,  227,  226,  225,  224,  223,  222,  220,  219,
      218,  216,  215,  214,  212,  211,  210,  208,  207,  206,
      205,  204,  203,  201,  200,  199,  198,  197,  196,  195,
      193,  191,  168,  164,  163,  162,  160,  156,  155,  154,
      152,  151,  149,  146,  145,  142,  140,  138,  137,  136,
      135,  134,  133,  132,  129,  128,  127,  126,  125,  123,
      122,  121,  120,  117,  116,  114,  113,  112,  111,  110,
      109,  104,  100,   84,   82,   69,   55,   49,   45,   44,
       42,   35,   28,   17,   11,    9,    5,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,

      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505,  505,  505,  505,
      505,  505,  505,  505,  505,  505,  505
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "120lex.l"
/*     120gram.l
       
       Ian Westrope
       CS 445


      The code for handling multiple input files aka includes I found in the
      flex manual.
*/
/*	$Id: lexer.l,v 1.2 1997/11/19 15:13:15 sandro Exp $	*/
/*
 * Copyright (c) 1997 Sandro Sigala <ssigala@globalnet.it>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * ISO C++ lexical analyzer.
 *
 * Based on the ISO C++ draft standard of December '96.
 */
#line 45 "120lex.l"
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>

#include "120gram.h"
#include "tree.h"

int lineno;

static int yywrap(void);
static void skip_until_eol(void);
static void skip_comment(void);
static int check_identifier(char *);
/* headerfile to use yypush_buffer in main.c */

#line 843 "lex.yy.c"

#define INITIAL 0
#define include 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 73 "120lex.l"


#line 1029 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 506 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 688 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 75 "120lex.l"
{ ++lineno; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 76 "120lex.l"
{ /* Ignore whitespace. */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 78 "120lex.l"
{ skip_comment(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 79 "120lex.l"
{ skip_until_eol(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 82 "120lex.l"
{ BEGIN (include); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 83 "120lex.l"

	YY_BREAK
case 7:
YY_RULE_SETUP
#line 84 "120lex.l"
{ printf("found iostream\n"); 
                         BEGIN (INITIAL); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 86 "120lex.l"
{ printf("found cstdlib\n");
                         BEGIN (INITIAL); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 88 "120lex.l"
{ printf("found ctime\n");
                         BEGIN (INITIAL); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 90 "120lex.l"
{ printf("found string\n");
                         BEGIN (INITIAL); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 92 "120lex.l"
{ printf("found fstream\n");
                         BEGIN (INITIAL); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 94 "120lex.l"
{ printf("found user include\n");
                              
                              int len = strlen(yytext) - 2;
                              char *filename = (char *)calloc(len, sizeof(char));
                              strncpy(filename, yytext+1, len);
                              filename[len] = '\0';
                              printf("%s\n", filename);

                              yyin = fopen( filename, "r");
                              if( !yyin ){
                                printf("couldn't open include file\n");
                              }              
               
                              yypush_buffer_state(yy_create_buffer(yyin,YY_BUF_SIZE));
                              BEGIN(INITIAL); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 110 "120lex.l"
{yylval.np = alcleaf('{', yytext); return '{'; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 111 "120lex.l"
{ return '{'; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 112 "120lex.l"
{ return '}'; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 113 "120lex.l"
{ return '}'; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 114 "120lex.l"
{ return '['; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 115 "120lex.l"
{ return '['; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 116 "120lex.l"
{ return ']'; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 117 "120lex.l"
{ return ']'; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 118 "120lex.l"
{ return '('; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 119 "120lex.l"
{ return ')'; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 120 "120lex.l"
{ return ';'; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 121 "120lex.l"
{ return ':'; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 122 "120lex.l"
{ return ELLIPSIS; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 123 "120lex.l"
{ return '?'; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 124 "120lex.l"
{ return COLONCOLON; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 125 "120lex.l"
{ return '.'; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 126 "120lex.l"
{ return DOTSTAR; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 127 "120lex.l"
{ return '+'; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 128 "120lex.l"
{ return '-'; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 129 "120lex.l"
{ return '*'; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 130 "120lex.l"
{ return '/'; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 131 "120lex.l"
{ return '%'; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 132 "120lex.l"
{ return '^'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 133 "120lex.l"
{ return '^'; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 134 "120lex.l"
{ return '&'; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 135 "120lex.l"
{ return '&'; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 136 "120lex.l"
{ return '|'; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 137 "120lex.l"
{ return '|'; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 138 "120lex.l"
{ return '~'; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 139 "120lex.l"
{ return '~'; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 140 "120lex.l"
{ return '!'; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 141 "120lex.l"
{ return '!'; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 142 "120lex.l"
{ return '='; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 143 "120lex.l"
{ return '<'; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 144 "120lex.l"
{ return '>'; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 145 "120lex.l"
{ return ADDEQ; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 146 "120lex.l"
{ return SUBEQ; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 147 "120lex.l"
{ return MULEQ; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 148 "120lex.l"
{ return DIVEQ; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 149 "120lex.l"
{ return MODEQ; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 150 "120lex.l"
{ return XOREQ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 151 "120lex.l"
{ return XOREQ; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 152 "120lex.l"
{ return ANDEQ; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 153 "120lex.l"
{ return ANDEQ; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 154 "120lex.l"
{ return OREQ; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 155 "120lex.l"
{ return OREQ; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 156 "120lex.l"
{ return SL; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 157 "120lex.l"
{ return SR; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 158 "120lex.l"
{ return SLEQ; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 159 "120lex.l"
{ return SREQ; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 160 "120lex.l"
{ return EQ; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 161 "120lex.l"
{ return NOTEQ; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 162 "120lex.l"
{ return NOTEQ; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 163 "120lex.l"
{ return LTEQ; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 164 "120lex.l"
{ return GTEQ; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 165 "120lex.l"
{ return ANDAND; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 166 "120lex.l"
{ return ANDAND; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 167 "120lex.l"
{ return OROR; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 168 "120lex.l"
{ return OROR; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 169 "120lex.l"
{ return PLUSPLUS; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 170 "120lex.l"
{ return MINUSMINUS; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 171 "120lex.l"
{ return ','; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 172 "120lex.l"
{ return ARROWSTAR; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 173 "120lex.l"
{ return ARROW; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 175 "120lex.l"
{ return ASM; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 176 "120lex.l"
{ return AUTO; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 177 "120lex.l"
{ return BOOL; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 178 "120lex.l"
{ return BREAK; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 179 "120lex.l"
{ return CASE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 180 "120lex.l"
{ return CATCH; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 181 "120lex.l"
{ return CHAR; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 182 "120lex.l"
{ return CLASS; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 183 "120lex.l"
{ return CONST; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 184 "120lex.l"
{ return CONST_CAST; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 185 "120lex.l"
{ return CONTINUE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 186 "120lex.l"
{ return DEFAULT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 187 "120lex.l"
{ return DELETE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 188 "120lex.l"
{ return DO; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 189 "120lex.l"
{ return DOUBLE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 190 "120lex.l"
{ return DYNAMIC_CAST; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 191 "120lex.l"
{ return ELSE; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 192 "120lex.l"
{ return ENUM; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 193 "120lex.l"
{ return EXPLICIT; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 194 "120lex.l"
{ return EXPORT; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 195 "120lex.l"
{ return EXTERN; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 196 "120lex.l"
{ return FALSE; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 197 "120lex.l"
{ return FLOAT; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 198 "120lex.l"
{ return FOR; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 199 "120lex.l"
{ return FRIEND; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 200 "120lex.l"
{ return GOTO; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 201 "120lex.l"
{ return IF; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 202 "120lex.l"
{ return INLINE; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 203 "120lex.l"
{ return INT; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 204 "120lex.l"
{ return LONG; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 205 "120lex.l"
{ return MUTABLE; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 206 "120lex.l"
{ return NAMESPACE; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 207 "120lex.l"
{ return NEW; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 208 "120lex.l"
{ return OPERATOR; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 209 "120lex.l"
{ return PRIVATE; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 210 "120lex.l"
{ return PROTECTED; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 211 "120lex.l"
{ return PUBLIC; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 212 "120lex.l"
{ return REGISTER; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 213 "120lex.l"
{ return REINTERPRET_CAST; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 214 "120lex.l"
{ return RETURN; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 215 "120lex.l"
{ return SHORT; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 216 "120lex.l"
{ return SIGNED; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 217 "120lex.l"
{ return SIZEOF; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 218 "120lex.l"
{ return STATIC; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 219 "120lex.l"
{ return STATIC_CAST; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 220 "120lex.l"
{ return STRUCT; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 221 "120lex.l"
{ return SWITCH; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 222 "120lex.l"
{ return TEMPLATE; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 223 "120lex.l"
{ return THIS; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 224 "120lex.l"
{ return THROW; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 225 "120lex.l"
{ return TRUE; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 226 "120lex.l"
{ return TRY; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 227 "120lex.l"
{ return TYPEDEF; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 228 "120lex.l"
{ return TYPEID; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 229 "120lex.l"
{ return TYPENAME; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 230 "120lex.l"
{ return UNION; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 231 "120lex.l"
{ return UNSIGNED; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 232 "120lex.l"
{ return USING; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 233 "120lex.l"
{ return VIRTUAL; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 234 "120lex.l"
{ return VOID; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 235 "120lex.l"
{ return VOLATILE; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 236 "120lex.l"
{ return WCHAR_T; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 237 "120lex.l"
{ return WHILE; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 239 "120lex.l"
{ return check_identifier(yytext); }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 241 "120lex.l"
{ return INTEGER; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 242 "120lex.l"
{ return INTEGER; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 243 "120lex.l"
{ return INTEGER; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 245 "120lex.l"
{ return FLOATING; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 246 "120lex.l"
{ return FLOATING; }
	YY_BREAK
case 146:
/* rule 146 can match eol */
YY_RULE_SETUP
#line 248 "120lex.l"
{ return CHARACTER; }
	YY_BREAK
case 147:
/* rule 147 can match eol */
YY_RULE_SETUP
#line 249 "120lex.l"
{ return CHARACTER; }
	YY_BREAK
case 148:
/* rule 148 can match eol */
YY_RULE_SETUP
#line 251 "120lex.l"
{ return STRING; }
	YY_BREAK
case 149:
/* rule 149 can match eol */
YY_RULE_SETUP
#line 252 "120lex.l"
{ return STRING; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 254 "120lex.l"
{ fprintf(stderr, "%d: unexpected character `%c'\n", lineno, yytext[0]); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(include):
#line 256 "120lex.l"
{
     	  yypop_buffer_state();
     
          if ( !YY_CURRENT_BUFFER )
          {
            yyterminate();
          }
        }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 266 "120lex.l"
ECHO;
	YY_BREAK
#line 1903 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 506 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 506 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 505);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 266 "120lex.l"



static int
yywrap(void)
{
	return 1;
}

/*
 * We use this routine instead a lex pattern because we don't need
 * to save the matched comment in the `yytext' buffer.
 */
static void
skip_comment(void)
{
	int c1, c2;

	c1 = input();
	c2 = input();

	while (c2 != EOF && !(c1 == '*' && c2 == '/')) {
		if (c1 == '\n')
			++lineno;
		c1 = c2;
		c2 = input();
	}
}

/*
 * See the previous comment for an explanation.
 */
static void
skip_until_eol(void)
{
	int c;

	while ((c = input()) != EOF && c != '\n')
		;
	++lineno;
}

/*
 * Type name table.
 * Replace this with a hash table, when you get a chance.
 */
struct typenametable_entry {
   char *name;
   int category;
   struct typenametable_entry *next;
   } *head;

int typenametable_lookup(char *s)
{
   struct typenametable_entry *tmp = head;
   while (tmp) {
      if (!strcmp(s, tmp->name)) return tmp->category;
      tmp = tmp->next;
   }
   return IDENTIFIER;
}

int typenametable_insert(char *s, int cat)
{
   struct typenametable_entry *tmp = head;
   while (tmp) {
      if (!strcmp(s, tmp->name)) {
         fprintf(stderr,
	    "warning, %s is already in the typename table as a %d\n",
	    s, tmp->category );
         return tmp->category;
         }
      tmp = tmp->next;
   }
   tmp = calloc(1, sizeof (struct typenametable_entry));
   if(!tmp) { fprintf(stderr, "tnti out of memory\n"); return -1; }
   tmp->name = strdup(s);
   tmp->category = cat;
   tmp->next = head;
   head = tmp;
}

static int
check_identifier(char *s)
{
	return typenametable_lookup(s);
}

